vich_uploader:
    db_driver: orm

    mappings:
        products_images:
            uri_prefix: /uploads/products_images
            upload_destination: '%kernel.project_dir%/public/uploads/products_images'
            namer: vich_uploader.namer_origname
